version: 0.2

env:
#  shell: /bin/bash
  variables:
    DOCKER_BUILDKIT: 1
    TF_VERSION: 0.14.5
    AWS_RETRY_MODE: adaptive
    AWS_MAX_ATTEMPTS: 5

phases:
#  install:
#    commands:
#      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
#      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - ./buildspec-install.sh
#      - aws s3 cp "s3://tools/$(./pipeline/get-bootstrap-resource.sh --resource=s3)/terraform_${TF_VERSION}_linux_amd64.zip" /tmp/terraform.zip
#      - unzip /tmp/terraform.zip -d /usr/local/bin && rm /tmp/terraform.zip
  build:
    commands:
      - aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "$(./get-account-id.sh).dkr.ecr.${AWS_REGION}.amazonaws.com"
      - make build-functions deploy-application